#!/bin/bash

echo "========================================="
echo "Google Cloud 認証セットアップ"
echo "========================================="
echo ""
echo "以下の手順で認証を完了してください："
echo ""
echo "1. ターミナルで以下のコマンドを実行してください："
echo "   cd /home/khirota/dev/basket-info-server"
echo "   ./google-cloud-sdk/bin/gcloud auth login"
echo ""
echo "2. ブラウザが自動的に開かない場合は、表示される URL を手動でブラウザで開いてください"
echo ""
echo "3. Google アカウントでログインして認証を完了してください"
echo ""
echo "認証が完了したら、以下のコマンドでプロジェクトを設定してください："
echo "   ./google-cloud-sdk/bin/gcloud config set project YOUR_PROJECT_ID"
echo ""
echo "プロジェクト ID がわからない場合は："
echo "   ./google-cloud-sdk/bin/gcloud projects list"
echo ""
